<?php
error_reporting(E_ALL); ini_set('display_errors', '1');

echo "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\n";
echo "<html xmlns=\"http://www.w3.org/1999/xhtml\">\n";
echo "<head>\n";
echo "	<title>Raspberry PI Status</title>\n";
echo "	<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-15\" />\n";
echo "  <meta http-equiv=\"refresh\" content=\"90\" >";
echo "  <link rel=\"stylesheet\" href=\"stylesheet.css\">";
echo "  <link rel=\"stylesheet\" href=\"styledisplay.css\">";
echo "  <script language=\"JavaScript\" type=\"text/javascript\">\n";
echo "    function bildwechsel(Bildname)\n";
echo "    {\n";
echo "	  if(document.getElementById(Bildname).src.indexOf('1_Modules.png') == -1)\n";
echo "      {\n";
echo "         document.getElementById(Bildname).src = \"1_Modules.png\"\n";
echo "      } else {\n";
echo "         document.getElementById(Bildname).src = \"2_Absolute_Humidity.png\"\n";
echo "      }\n";
echo "    }\n";
echo "  </script>\n";
echo "</head>\n";
echo "<body>\n";

include 'conf.php';
include 'functions.php';

echo "<div  class=\"stframe\">\n";
    echo "<div  class=\"stleft\">\n";
        echo "<div  class=\"sttitle\">\n";
            echo "Raspberry PI SensorTool Status: ". date("d.m.Y",time())."\n";
        echo "</div>\n";
        echo "<div  class=\"stwebradio\">\n";
	  		$vWebFrame = 'rpidisplay';
	  		include 'webradio_frame.php';
        echo "</div>\n";
        echo "<div  class=\"stsensor\">\n";
        	$vSensor_Frame = 'rpidisplay';
            include 'sensor.php';
        echo "</div>\n";
        echo "<div  class=\"stfa\">\n";
            include 'fa.php';
        echo "</div>\n";        
    echo "</div>\n";
    echo "<div  class=\"stright\">\n";
        echo "<div  class=\"stdiagAH\">\n";
            echo "<img class=\"chart\" src=2_Absolute_Humidity.png name=\"grafik\" id=\"grafik\" onClick=\"bildwechsel(this.name)\" />\n";
        echo "</div>\n";
        echo "<div  class=\"stmodules\">\n";
            include 'module.php';
        echo "</div>\n";
    echo "</div>\n";
    echo "<br style=\"clear:both;\" />\n";
    echo "<div  class=\"stbottom\">\n";
        echo "<div  class=\"stlink\">\n";
	    	$vMenueFrame = 'rpidisplay';  
	    	include 'top_menue.php';
        echo "</div>\n";
    echo "</div>\n";
    echo "<div  class=\"stbottom\">\n";
        echo "<div  class=\"sthistory\">\n";
            include 'loglatestentry7.php';
        echo "</div>\n";
    echo "</div>\n";
echo "</div>\n";
echo "</body>\n";
?>
