<?php
echo "<table class=\"topmenu7\">\n";
echo "  <TR>\n";
echo "    <TD class=\"topmenu7\">\n";
echo "      <form action=\"http://raspberrypi3/index_kiosk.php\">\n";
echo "        <input type=\"submit\" value=\"Home\" />\n";
echo "      </form>\n";
echo "    </TD>\n";
echo "    <TD class=\"topmenu7\">\n";
echo "      <form action=\"http://raspberrypi3/switch7.php\">\n";
echo "        <input type=\"submit\" value=\"Schalter\" />\n";
echo "      </form>\n";
echo "    </TD>\n";
echo "    <TD class=\"topmenu7\">\n";
echo "      <form action=\"http://raspberrypi3/overview.php\">\n";
echo "      <form action=\"http://raspberrypi/slideshow.php\">\n";
echo "        <input type=\"submit\" value=\"slideshow\" />\n";
echo "      </form>\n";
echo "    </TD>\n";
echo "    <TD class=\"topmenu7\">\n";
echo "      <form action=\"http://raspberrypi/overview.php\">\n";
echo "        <input type=\"submit\" value=\"Diagramme\" />\n";
echo "      </form>\n";
echo "    </TD>\n";
echo "    <TD class=\"topmenu7\">\n";
echo "      <form action=\"http://raspberrypi3/settings.php\">\n";
echo "        <input type=\"submit\" value=\"Einstellungen\" />\n";
echo "      </form>\n";
echo "    </TD>\n";
echo "    <TD class=\"topmenu7\">\n";
echo "      <form action=\"http://raspberrypi3/index.php\">\n";
echo "        <input type=\"submit\" value=\"Index\" />\n";
echo "      </form>\n";
echo "    </TD>\n";
echo "  </TR>\n";
echo "</table>\n";
?>
