<?php
echo "<table class=\"topmenu\">\n";
echo "  <TR>\n";
echo "    <TD class=\"topmenu\">\n";
echo "      <form action=\"http://raspberrypi/index_kiosk.php\">\n";
echo "        <input type=\"submit\" value=\"Home\" />\n";
echo "      </form>\n";
echo "    </TD>\n";
echo "    <TD class=\"topmenu\">\n";
echo "      <form action=\"http://raspberrypi/index.php\">\n";
echo "        <input type=\"submit\" value=\"Index\" />\n";
echo "      </form>\n";
echo "    </TD>\n";
echo "    <TD class=\"topmenu\">\n";
echo "      <form action=\"http://raspberrypi/picam.php\">\n";
echo "        <input type=\"submit\" value=\"Picam\" />\n";
echo "      </form>\n";
echo "    </TD>\n";
echo "    <TD class=\"topmenu\">\n";
echo "      <form action=\"http://raspberrypi/settings.php\">\n";
echo "        <input type=\"submit\" value=\"Einstellungen\" />\n";
echo "      </form>\n";
echo "    </TD>\n";
echo "    <TD class=\"topmenu\">\n";
echo "      <form action=\"http://raspberrypi/overview.php\">\n";
echo "        <input type=\"submit\" value=\"Diagramme\" />\n";
echo "      </form>\n";
echo "    </TD>\n";
echo "    <TD class=\"topmenu\">\n";
echo "      <form action=\"http://raspberrypi/switch.php\">\n";
echo "        <input type=\"submit\" value=\"Schalter\" />\n";
echo "      </form>\n";
echo "    </TD>\n";
echo "    <TD class=\"topmenu\">\n";
echo "      <form action=\"http://raspberrypi/webradio.php\">\n";
echo "        <input type=\"submit\" value=\"webradio\" />\n";
echo "      </form>\n";
echo "    </TD>\n";
echo "  </TR>\n";
echo "</table>\n";
?>
